spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mylocal:3306/test?&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123abcABC
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: false
  cloud:
    config:
      enabled: false
  redis:
    host: mylocal
server:
  port: 8083
logging:
    level:
        org:
            hibernate:
                SQL: info
                type:
                    descriptor:
                        sql: info
eureka:
  client:
    service-url:
      defaultZone: http://mylocal:7001/eureka
  instance:
      prefer-ip-address: true
      # "spring.cloud.client.ipAddress" has changed to "spring.cloud.client.ip-address" since SpringCloud.Finchley
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
feign:
  hystrix:
     enabled: true
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000
  eager-load:
    enabled: true
    clients:
      - inventory-service
      - pricing-service
# custom config
categoryIds: A,B,C,D
maxProductCountInCategory: 1000000
checkProductExistBeforeAdding: true
pageSize: 20
productBatchSize : 1000