#version: '3'
# to use memory limit feature in docker-compose, downgrade version to '2'
version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123abcABC
  redis:
    image: redis
    ports:
      - "6379:6379"
  discovery-service:
    mem_limit: 2048M
    image: springcloudstudy_discovery-service
    entrypoint: java -jar /app.jar
    ports:
     - "7001:7001"
    restart: always
    extra_hosts:
     mylocal: $MYLOCAL_IP
  pricing-service:
    mem_limit: 2048M
    image: springcloudstudy_pricing-service
    entrypoint: java -jar /app.jar
    ports:
     - "8081:8081"
    links:
     - discovery-service
    depends_on:
     - discovery-service
    restart: always
    extra_hosts:
     localhost: $MYLOCAL_IP
  inventory-service:
    mem_limit: 2048M
    image: springcloudstudy_inventory-service
    entrypoint: java -jar /app.jar
    ports:
     - "8082:8082"
    links:
     - discovery-service
    depends_on:
     - discovery-service
    restart: always
    extra_hosts:
     localhost: $MYLOCAL_IP
  catalog-service:
    mem_limit: 2048M
    image: springcloudstudy_catalog-service
    entrypoint: java -jar /app.jar
    ports:
     - "8083:8083"
    links:
     - discovery-service
    depends_on:
     - discovery-service
    restart: always
    extra_hosts:
     localhost: $MYLOCAL_IP
  web-storefront:
    mem_limit: 2048M
    image: springcloudstudy_web-storefront
    entrypoint: java -jar /app.war # notice: storefront should be .war to include jsp pages, not .jar
    ports:
     - "8080:8080"
    links:
     - discovery-service
    depends_on:
     - discovery-service
    restart: always
    extra_hosts:
     localhost: $MYLOCAL_IP