#version: '3'
# to use memory limit feature in docker-compose, should downgrade version to '2'
version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123abcABC
  discovery-service:
    mem_limit: 1280M
    image: springcloudstudy_discovery-service
    entrypoint: java -jar /app.jar
    ports:
     - "7000:7000"
    environment:
     - server.port=$EUREKA_SERVER_PORT
    restart: always
  pricing-service:
    mem_limit: 1280M
    image: springcloudstudy_pricing-service
    entrypoint: java -jar /app.jar
    ports:
     - "8081:8081"
    environment:
     - server.port=8081
     - eurekaClientServiceUrlDefaultZone=http://$EUREKA_SERVER_IP:$EUREKA_SERVER_PORT/eureka
    links:
     - discovery-service
    depends_on:
     - discovery-service
    restart: always
  inventory-service:
    mem_limit: 1280M
    image: springcloudstudy_inventory-service
    entrypoint: java -jar /app.jar
    ports:
     - "8082:8082"
    environment:
     - server.port=8082
     - eurekaClientServiceUrlDefaultZone=http://$EUREKA_SERVER_IP:$EUREKA_SERVER_PORT/eureka
    links:
     - discovery-service
    depends_on:
     - discovery-service
    restart: always
  catalog-service:
    mem_limit: 1280M
    image: springcloudstudy_catalog-service
    entrypoint: java -jar /app.jar
    ports:
     - "8083:8083"
    environment:
     - server.port=8083
     - eurekaClientServiceUrlDefaultZone=http://$EUREKA_SERVER_IP:$EUREKA_SERVER_PORT/eureka
    links:
     - discovery-service
    depends_on:
     - discovery-service
    restart: always
  web-storefront:
    mem_limit: 1280M
    image: springcloudstudy_web-storefront
    entrypoint: java -jar /app.jar
    ports:
     - "9000:9000"
    environment:
     - server.port=9000
     - eurekaClientServiceUrlDefaultZone=http://$EUREKA_SERVER_IP:$EUREKA_SERVER_PORT/eureka
    links:
     - discovery-service
    depends_on:
     - discovery-service
    restart: always