spring:
  application:
    name: pricing-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.118.200:3306/test?&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123abcABC
  jpa:
    database: mysql
    hibernate:
        ddl-auto: update
    show-sql: true
server:
  port: 8081
#eureka:
#  client:
#    service-url:
#      defaultZone: ${eurekaClientServiceUrlDefaultZone}
#  instance:
#      prefer-ip-address: true