spring:
  application:
    name: discovery-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.118.200:3306/test?&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123abcABC
  jpa:
    database: mysql
    hibernate:
        ddl-auto: update
    show-sql: true
server:
  port: 7000
#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
#  server:
#    enable-self-preservation: true