spring:
  application:
    name: discovery-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mylocal:3306/test?&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123abcABC
  jpa:
    database: mysql
    hibernate:
        ddl-auto: none
    show-sql: true
  cloud:
    config:
      enabled: false
  redis:
    host: mylocal
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: mylocal:9300
      cluster-name: docker-cluster # MAKE SURE this name is right, you can get from mylocal:9200
      properties:
        transport:
          tcp:
            connect_timeout: 10s
server:
  port: 7001
eureka:
  client:
    registry-fetch-interval-seconds: 10 # default:30
    healthcheck:
      # this feature is used by:
      # org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration.EurekaHealthCheckHandlerConfiguration
      enabled: true
    service-url:
      defaultZone: http://mylocal:7001/eureka
  instance:
    # "spring.cloud.client.ipAddress" has changed to "spring.cloud.client.ip-address" since SpringCloud.Finchley
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 # default:30
    lease-expiration-duration-in-seconds: 30 # default:90
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    home-page-url-path: /
  server:
    enable-self-preservation: true
management:
  health:
    status:
      http-mapping:
        UNKNOWN: 503 # default:200
  endpoint:
    health:
      show-details: always # default:never
  endpoints:
    web:
      exposure:
        # all available endpoints refer to:
        # https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints
        include: "*"
        # there is a bug between SpringBoot2.0.2 and SpringCloud.Finchley.RC1
        # must exclude "env" endpoints, otherwise will throw java.lang.IllegalStateException when app startup
        # refers: https://github.com/spring-cloud/spring-cloud-commons/issues/354
        exclude: env