spring:
  application:
    name: web-storefront
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.118.200:3306/test?&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123abcABC
  jpa:
    database: mysql
    hibernate:
        ddl-auto: none
    show-sql: true
  # support jsp view
#  mvc:
#    view:
#      prefix: /WEB-INF/page/
#      suffix: .jsp
logging:
    level:
        org:
            hibernate:
                SQL: debug
                type:
                    descriptor:
                        sql: trace
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://172.17.118.200:7000/eureka
  instance:
      prefer-ip-address: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
feign:
  hystrix:
     enabled: true
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  eager-load:
    enabled: true
    clients:
      - catalog-service
